# .github/workflows/start-codespace.yml
name: Start Codespace (Background)

on:
  workflow_dispatch:
    inputs:
      codespace_name:
        description: 'Codespace name to start'
        required: true
        type: string

jobs:
  start-codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Start existing codespace
        env:
          GH_TOKEN: ${{ secrets.PAT1 }}
        run: |
          #echo '-------- env begin --------'
          #env
          #echo '-------- env end --------'
          #which gh
          #gh codespace list
          cs=${{github.event.inputs.codespace_name}}
          #echo "cs=$cs"
          echo "---- start codespace $cs ----"
          # gh codespace start -c $cs || true # no 'start', use curl API
          curl -H "Authorization: Bearer $GH_TOKEN" -H "Accept: application/vnd.github+json" \
            https://api.github.com/user/codespaces/$cs/start -X POST | jq .state
          n=10
          for i in $(seq $n); do
            state=$(gh codespace list --json name,state \
              -q ".[] | select(.name == \"$cs\") | .state")
            echo "[$i/$n] State: $state"
            [ "$state" = "Available" ] && break
            sleep 3
          done
          [ $i = $n ] && echo 'Start Failed.' && exit 1
          gh codespace -c $cs ssh 'sudo su -c "echo 127.0.0.1 t >> /etc/hosts"'
          echo "---- try to start gost ----"
          gh codespace -c $cs ssh "nohup gost.ss1.sh >/tmp/gost.log 2>&1 &" || echo gost.ss1.sh failed
          gh codespace -c $cs ssh "pgrep gost" || echo no gost
          a='ok'
          timeout 20 gh codespace -c $cs ports forward 8888:8888 2222:2222 || a='fail'  # timeout to break stuck!!! always stuck!!
          echo port-forward $a
          a='ok'
          timeout 20 gh codespace -c $cs ports visibility 8888:public || a='fail'  # true/echo to avoid exit with error
          echo port-vis $a
          echo '---- End, maybe ok, maybe not. ----'
